@ECommerce_API_HostAddress = https://localhost:44347

### Get all categories
GET {{ECommerce_API_HostAddress}}/api/categories
Accept: application/json

###

### Get category by ID
GET {{ECommerce_API_HostAddress}}/api/categories/1
Accept: application/json

###

### Create category
POST {{ECommerce_API_HostAddress}}/api/categories
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Electronic devices and accessories"
}

### Create Category

POST {{ECommerce_API_HostAddress}}/api/categories
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Electronic devices and accessories"
}

### Create Product

POST {{ECommerce_API_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Gaming Laptop",
  "description": "High performance gaming laptop",
  "price": 250000,
  "stockQuantity": 10,
  "imageUrl": "https://example.com/laptop.jpg",
  "categoryId": 1
}


### Get Products

GET {{ECommerce_API_HostAddress}}/api/products
Accept: application/json

### Register

POST {{ECommerce_API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Mubasher",
  "lastName": "Developer",
  "email": "mubasher@example.com",
  "password": "Password123!"
}

### Login

POST {{ECommerce_API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "mubasher@example.com",
  "password": "Password123!"
}

### Public endpoint

GET {{ECommerce_API_HostAddress}}/api/test/public

### Protected endpoint

GET {{ECommerce_API_HostAddress}}/api/test/protected

### Protected endpoint

GET {{ECommerce_API_HostAddress}}/api/test/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtdWJhc2hlckBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzg5NDU4MDQ3LCJpc3MiOiJFQ29tbWVyY2UuQVBJIiwiYXVkIjoiRUNvbW1lcmNlLkFuZ3VsYXIifQ._uK7Zcfiu3jTNNOhWhwDPeCxQbd8qjbRicGS16KU84Q